package Enums;

import java.io.Serializable;

public enum EKidQ implements Serializable {
    STRUCTURE_FAMILIALE,
    DYNAMIQUE_FAMILIALE,
    ANTECEDENTS_FAMILIAUX,
    CONDITIONS_NATALE,
    DEVELOPPEMENT_PSYCHOMOTEUR,
    DEVELOPPEMENT_LANGAGIER,
    CARACTERE_COMPORTEMENT
    }
