package Enums;

public enum EKidQ {
    STRUCTURE_FAMILIALE,
    DYNAMIQUE_FAMILIALE,
    ANTECEDENTS_FAMILIAUX,
    CONDITIONS_NATALE,
    DEVELOPPEMENT_PSYCHOMOTEUR,
    DEVELOPPEMENT_LANGAGIER,
    CARACTERE_COMPORTEMENT
    }
